[load_balancer]
address = "127.0.0.1"
port = 8080
algorithm = "round_robin"
layer = "L7"

[[server]]
address = "127.0.0.1"
port = 3000
max_connections = 1000
weight = 1

[[server]]
address = "127.0.0.1"
port = 3001
max_connections = 1000
weight = 1
